# Generated by Django 2.1.1 on 2018-10-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
