# Generated by Django 2.1.1 on 2018-10-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0002_remove_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
    ]
