# Generated by Django 2.1.1 on 2018-10-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0003_auto_20181001_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
